version: 2
updates:
  - package-ecosystem: pnpm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /apps/web
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /apps/api
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
